language: minimal
sudo: required
services:
  - docker
before_install:
  - docker pull debian:buster-slim
  - docker run --name build --rm --detach --interactive --mount type=bind,src=`pwd`,dst=/build debian:buster-slim /bin/sh
  - docker ps -a
  - docker exec -u root build apt-get -y update
  - docker exec -u root build apt-get --no-install-recommends -y install make gcc gcc-multilib gcc-mingw-w64 autoconf automake libtool pkg-config ca-certificates wget sed git-core golang-go moreutils zip go-dep
script:
  - travis_wait 40 docker exec build /build/.travis-make.sh make 3rdparty-all
  - docker exec build make -C /build unit-test
  - docker exec build make -C /build release
after_script:
  - docker exec build ls -l /build /build/_3rdparty/archive /build/_build/*
after_failure:
  - tail -n 1000 .travis-make.log
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure:
  file_glob: true
  file: spyre-*.zip
  on:
    repo: spyre-project/spyre
    tags: true
