[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "master"
  name = "github.com/daaku/go.zipexe"
